version: "3.7"

services:
  # frontend:
  #   build: ./services/frontend
  #   command: python manage.py run -h 0.0.0.0
  #   volumes:
  #     - ./services/frontend/:/usr/src/app/
  #   ports:
  #     - 5001:5001
  #   env_file:
  #     - ./.env.dev

  # web:
  #   build: ./services/web
  #   command: python manage.py runserver 0.0.0.0:5002
  #   volumes:
  #     - ./services/web/:/usr/src/app/
  #   ports:
  #     - 5002:5002
  #   env_file:
  #     - ./.env.dev
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data

volumes:
  postgres_data:
